name: Release on manual push

on:
  workflow_dispatch:
    inputs:
      release_version:
        description: 'Release version'
        required: true

jobs:
  version:
    uses: walt-id/waltid-identity/.github/workflows/version.yml@266f5c09359450c39019a6da38f2b331e7122918
    with:
      preferred: ${{ inputs.release_version }}
  gradle:
    uses: walt-id/waltid-identity/.github/workflows/gradle.yml@3c360ff47f15ed48833e75df5fc39c6a22356912
    secrets: inherit
    needs: version
    with:
      version: ${{ needs.version.outputs.release_version }}
      publish: true
  docker-matrix:
    uses: walt-id/waltid-identity/.github/workflows/load-json.yml@927c4233610e90dd8a57418662fad7293b7b29a4
    with:
      jsonpath: ".github/workflows/data/docker-matrix.json"
  docker:
    uses: walt-id/waltid-identity/.github/workflows/docker.yml@69b0349a4d83b3183475baf7cd512d54f5541af8
    secrets: inherit
    needs: [ version, docker-matrix ]
    with:
      images: ${{ needs.docker-matrix.outputs.json }}
      version: ${{ needs.version.outputs.release_version }}
      tag: latest
      publish: true
  api-docker-matrix:
    uses: walt-id/waltid-identity/.github/workflows/load-json.yml@927c4233610e90dd8a57418662fad7293b7b29a4
    with:
      jsonpath: ".github/workflows/data/api-docker-matrix.json"
  api-docker:
    uses: walt-id/waltid-identity/.github/workflows/api-docker.yml@563c196ae5dcbfdbaa1cd5d9a08d94efc331fa34
    secrets: inherit
    needs: [ version, api-docker-matrix ]
    with:
      images: ${{ needs.api-docker-matrix.outputs.json }}
      version: ${{ needs.version.outputs.release_version }}
      publish: true
  deploy:
    uses: walt-id/waltid-identity/.github/workflows/deployment.yml@3c360ff47f15ed48833e75df5fc39c6a22356912
    secrets: inherit
    needs: [ version, gradle, docker, api-docker ]
    with:
      version: ${{ needs.version.outputs.release_version }}
      deployment: ${{ contains(needs.version.outputs.release_version, 'PRE-RELEASE') && 'dev' || 'prod' }}
      oss: ${{ contains(needs.version.outputs.release_version, 'PRE-RELEASE') && 'test-identity-main' || 'identity-main' }}
      enterprise: ${{ contains(needs.version.outputs.release_version, 'PRE-RELEASE') && 'test-enterprise-main' || 'enterprise-main' }}
  tag:
    uses: walt-id/waltid-identity/.github/workflows/tag.yml@266f5c09359450c39019a6da38f2b331e7122918
    needs: [ version, deploy ]
    with:
      version: ${{ needs.version.outputs.release_version }}
  enterprise-tag:
    uses: walt-id/waltid-identity/.github/workflows/enterprise-tag.yml@cf46ed618f9b296fd9b63c7207ca288855bb5343
    secrets: inherit
    needs: [ version, deploy ]
    with:
      version: ${{ needs.version.outputs.release_version }}
  release:
    uses: walt-id/waltid-identity/.github/workflows/changelog.yml@cf46ed618f9b296fd9b63c7207ca288855bb5343
    secrets: inherit
    needs: [ tag ]
    with:
      tag: ${{ needs.tag.outputs.tag }}